default: &default
  is_ows_trial: no
  case_cohort: no
  make_riskscore: no

ows_trial: &ows_trial
  forestplot_script: cor_coxph_forestplots_ows.R
  is_ows_trial: yes
  case_cohort: yes
  make_riskscore: yes


moderna_trial: &moderna_trial
  <<: *ows_trial
  two_marker_timepoints: yes
  timepoints: [29, 57]
  subset_variable: None
  subset_value: All
  assays: [bindSpike, bindRBD, pseudoneutid50, pseudoneutid80, liveneutmn50]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD, PsV Neutralization 50% Titer, PsV Neutralization 80% Titer, Live Virus Micro Neut 50% Titer]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml), Pseudovirus-nAb ID80 (IU80/ml), Live Virus-mnAb ID50 (IU50/ml)]
  times: [B, Day29, Day57, Delta29overB, Delta57overB, Delta57over29]
  time_labels: [Day 1, Day 29, Day 57, D29 fold-rise over D1, D57 fold-rise over D1, D57 fold-rise over D29]

moderna_real: &moderna_real
  <<: *moderna_trial
  mapped_data: /trials/covpn/p3001/analysis/correlates/Part_A_Blinded_Phase_Data/adata/P3001ModernaCOVEimmunemarkerdata_correlates_originaldatafromModerna_v1.0_Oct28_2021.csv # raw data
  study_name: COVE

moderna_mock: &moderna_mock
  <<: *moderna_trial
  mapped_data: COVID_VEtrial_practicedata_primarystage1.csv
  study_name: MockCOVE


vat08m: &vat08m
  <<: *ows_trial
  two_marker_timepoints: yes
  timepoints: [22, 43]
  subset_variable: None
  subset_value: All
  times: [B, Day22, Day43, Delta22overB, Delta43overB, Delta43over22]
  time_labels: [Day 1, Day 22, Day 43, D22 fold-rise over D1, D43 fold-rise over D1, D43 fold-rise over D22]
  assays: [pseudoneutid50]
  assay_labels: [PsV Neutralization 50% Titer]
  assay_labels_short: [Pseudovirus-nAb ID50 (IU50/ml)]
  study_name: VAT08m
  mapped_data: /trials/covpn/p3005/analysis/mapping_immune_correlates/adata/COVID_Sanofi_realdata_20220624.csv
  

prevent19: &prevent19
  <<: *ows_trial
  two_marker_timepoints: no
  timepoints: [35]
  times: [B, Day35, Delta35overB]
  time_labels: [Day 1, Day 35, D35 fold-rise over D1]
  mapped_data: /trials/covpn/p3004/analysis/mapping_immune_correlates/adata/COVID_Novavax_realdata_20220506.csv 
  assays: [bindSpike, pseudoneutid50]
  assay_labels: [Binding Antibody to Spike, PsV Neutralization 50% Titer]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml)]
  study_name: PREVENT19
  
azd1222_base: &azd1222_base
  <<: *ows_trial
  two_marker_timepoints: yes
  timepoints: [29, 57]
  times: [B, Day29, Day57, Delta29overB, Delta57overB, Delta57over29]
  time_labels: [Day 1, Day 29, Day 57, D29 fold-rise over D1, D57 fold-rise over D1, D57 fold-rise over D29]
  mapped_data: /trials/covpn/p3002/analysis/mapping_immune_correlates/adata/COVID_AstraZeneca_realdata_20220506.csv 
  subset_variable: None
  subset_value: All
  study_name: AZD1222

azd1222: &azd1222
  <<: *azd1222_base
  assays: [pseudoneutid50]
  assay_labels: [PsV Neutralization 50% Titer]
  assay_labels_short: [Pseudovirus-nAb ID50 (IU50/ml)]

azd1222_bAb: &azd1222_bAb
  <<: *azd1222_base
  assays: [bindSpike]
  assay_labels: [Binding Antibody to Spike]
  assay_labels_short: [Anti Spike IgG (BAU/ml)]


janssen_trial: &janssen_trial
  <<: *ows_trial
  two_marker_timepoints: no
  timepoints: [29]
  times: [B, Day29, Delta29overB]
  time_labels: [Day 1, Day 29, D29 fold-rise over D1]



# following are for the part A dataset
janssen_trial_partA: &janssen_trial_partA
  <<: *janssen_trial
  mapped_data: /trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_realdata_PartAComplete_20220609.csv 
  assays: [bindSpike, bindRBD, pseudoneutid50, ADCP]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD, PsV Neutralization 50% Titer, Phagocytic Score]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml), Phagocytic Score]
  study_name: ENSEMBLE

janssen_pooled_partA: 
  <<: *janssen_trial_partA
  subset_variable: None
  subset_value: All

janssen_na_partA: 
  <<: *janssen_trial_partA
  subset_variable: Region
  subset_value: 0

janssen_la_partA: 
  <<: *janssen_trial_partA
  subset_variable: Region
  subset_value: 1

janssen_sa_partA: 
  <<: *janssen_trial_partA
  subset_variable: Region
  subset_value: 2


# following are for the EUA dataset
janssen_trial_real: &janssen_trial_real
  <<: *janssen_trial
  mapped_data: /trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_realdata_20220310.csv 
  assays: [bindSpike, bindRBD, pseudoneutid50]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD, PsV Neutralization 50% Titer]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml), Pseudovirus-nAb ID50 (IU50/ml)]
  study_name: ENSEMBLE

janssen_pooled_real: 
  <<: *janssen_trial_real
  subset_variable: None
  subset_value: All

janssen_na_real: 
  <<: *janssen_trial_real
  subset_variable: Region
  subset_value: 0

janssen_la_real: 
  <<: *janssen_trial_real
  subset_variable: Region
  subset_value: 1

janssen_sa_real: 
  <<: *janssen_trial_real
  subset_variable: Region
  subset_value: 2


  
janssen_trial_realADCP: &janssen_trial_realADCP
  <<: *janssen_trial
  mapped_data: /trials/covpn/p3003/analysis/mapping_immune_correlates/adata/COVID_ENSEMBLE_realdata_20220310.csv 
  assays: [ADCP]
  assay_labels: [Phagocytic Score]
  assay_labels_short: [Phagocytic Score]
  study_name: ENSEMBLE

janssen_pooled_realADCP: 
  <<: *janssen_trial_realADCP
  subset_variable: None
  subset_value: All

janssen_na_realADCP: 
  <<: *janssen_trial_realADCP
  subset_variable: Region
  subset_value: 0

janssen_la_realADCP: 
  <<: *janssen_trial_realADCP
  subset_variable: Region
  subset_value: 1

janssen_sa_realADCP: 
  <<: *janssen_trial_realADCP
  subset_variable: Region
  subset_value: 2




janssen_trial_mock: &janssen_trial_mock
  <<: *janssen_trial
  mapped_data: COVID_ENSEMBLE_practicedata.csv # raw data
  assays: [bindSpike, bindRBD]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to RBD]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti RBD IgG (BAU/ml)]
  study_name: MockENSEMBLE

janssen_pooled_mock:
  <<: *janssen_trial_mock
  subset_variable: None
  subset_value: All

janssen_na_mock:
  <<: *janssen_trial_mock
  subset_variable: Region
  subset_value: 0

janssen_la_mock:
  <<: *janssen_trial_mock
  subset_variable: Region
  subset_value: 1

janssen_sa_mock:
  <<: *janssen_trial_mock
  subset_variable: Region
  subset_value: 2



profiscov_base: &profiscov_base
  study_name: PROFISCOV
  case_cohort: yes
  mapped_data: /networks/cavd/Objective 4/GH-VAP/ID127-Gast/Data/mapping_immune_correlates/adata/COVID_Butantan_realdata_20220923.csv

profiscov: &profiscov
  <<: *profiscov_base
  two_marker_timepoints: yes
  timepoints: [43,91]
  times: [B, Day43, Day91, Delta43overB, Delta91overB, Delta91over43]
  time_labels: [Day 1, Day 43, Day 91, D43 fold-rise over D1, D91 fold-rise over D1, D91 fold-rise over D43]
  assays: [bindSpike, bindSpike_B.1.1.7, bindSpike_B.1.351, bindSpike_P.1, bindRBD, bindRBD_B.1.1.7, bindRBD_B.1.351, bindRBD_P.1, bindN]
  assay_labels: [Binding Antibody to Spike, Binding Antibody to Spike B.1.1.7, Binding Antibody to Spike B.1.351, Binding Antibody to Spike P.1, Binding Antibody to RBD, Binding Antibody to RBD B.1.1.7, Binding Antibody to RBD B.1.351, Binding Antibody to RBD P.1, Binding Antibody to Nucleocapsid]
  assay_labels_short: [Anti Spike IgG (BAU/ml), Anti Spike B.1.1.7 IgG (BAU/ml), Anti Spike B.1.351 IgG (BAU/ml), Anti Spike P.1 IgG (BAU/ml), Anti RBD IgG (BAU/ml), Anti RBD B.1.1.7 IgG (BAU/ml), Anti RBD B.1.351 IgG (BAU/ml), Anti RBD P.1 IgG (BAU/ml), Anti N IgG (BAU/ml)]

profiscov_lvmn: &profiscov_lvmn
  <<: *profiscov_base
  two_marker_timepoints: no
  timepoints: [43]
  times: [B, Day43, Delta43overB]
  time_labels: [Day 1, Day 43, D43 fold-rise over D1]
  assays: [liveneutmn50]
  assay_labels: [Live Virus Micro Neut 50% Titer]
  assay_labels_short: [Live Virus-mnAb ID50 (IU50/ml)]

  
